spring:
  sql:
    init:
      mode: never
      
  datasource:
    url: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tjdwnrud1@
    
    
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        formatsql: true
        show-sql: true
 