spring:
  sql:
    init:
      mode: never
      
  datasource:
    url: jdbc:oracle:thin:@211.171.152.242:1521
    driver-class-name: oracle.jdbc.OracleDriver
    username: com4in
    password: com4in201!!
    
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        formatsql: true
        show-sql: true
 